/**
 * Inventory Order Service
 * Handles purchase order workflow with approval and average cost calculations
 */

import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { postInventoryReceivedJournal } from './accountingPostings';

export interface InventoryOrder {
  id: string;
  order_number: string;
  product_id: string;
  location_id: string;
  size_variant?: string | null;
  quantity: number;
  unit_cost: number;
  total_cost: number;
  status: 'pending' | 'approved' | 'rejected' | 'received';
  notes?: string | null;
  requested_by: string;
  requested_by_email?: string | null;
  approved_by?: string | null;
  approved_at?: string | null;
  received_at?: string | null;
  created_at: string;
  updated_at: string;
  // Joined fields
  product?: {
    name: string;
    sku: string;
  };
  location?: {
    name: string;
  };
}

export interface CreateOrderInput {
  product_id: string;
  location_id: string;
  size_variant?: string;
  quantity: number;
  unit_cost: number;
  notes?: string;
  requested_by: string;
  requested_by_email?: string;
}

/**
 * Create a new inventory order
 */
export const createInventoryOrder = async (input: CreateOrderInput): Promise<InventoryOrder | null> => {
  try {
    const { data, error } = await supabase
      .from('inventory_orders')
      .insert({
        product_id: input.product_id,
        location_id: input.location_id,
        size_variant: input.size_variant || null,
        quantity: input.quantity,
        unit_cost: input.unit_cost,
        notes: input.notes || null,
        requested_by: input.requested_by,
        requested_by_email: input.requested_by_email || null,
        order_number: '' // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (error) throw error;

    toast.success('Purchase order created successfully');
    return data as InventoryOrder;
  } catch (error) {
    console.error('Error creating inventory order:', error);
    toast.error('Failed to create purchase order');
    return null;
  }
};

/**
 * Get all inventory orders with optional filters
 */
export const getInventoryOrders = async (filters?: {
  status?: string;
  requested_by?: string;
  location_id?: string;
}): Promise<InventoryOrder[]> => {
  try {
    let query = supabase
      .from('inventory_orders')
      .select(`
        *,
        product:products(name, sku),
        location:inventory_locations(name)
      `)
      .order('created_at', { ascending: false });

    if (filters?.status) {
      query = query.eq('status', filters.status);
    }
    if (filters?.requested_by) {
      query = query.eq('requested_by', filters.requested_by);
    }
    if (filters?.location_id) {
      query = query.eq('location_id', filters.location_id);
    }

    const { data, error } = await query;

    if (error) throw error;

    return (data || []) as InventoryOrder[];
  } catch (error) {
    console.error('Error fetching inventory orders:', error);
    toast.error('Failed to load orders');
    return [];
  }
};

/**
 * Get pending orders count for dashboard
 */
export const getPendingOrdersCount = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('inventory_orders')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'pending');

    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting pending orders count:', error);
    return 0;
  }
};

/**
 * Approve an inventory order - updates status and inventory with average cost
 */
export const approveInventoryOrder = async (
  orderId: string, 
  approvedBy: string
): Promise<boolean> => {
  try {
    // First, get the order details
    const { data: order, error: orderError } = await supabase
      .from('inventory_orders')
      .select('*')
      .eq('id', orderId)
      .single();

    if (orderError) throw orderError;
    if (!order) throw new Error('Order not found');
    if (order.status !== 'pending') {
      toast.error('Order has already been processed');
      return false;
    }

    // Get current inventory for this product/location/variant
    let inventoryQuery = supabase
      .from('inventory_items')
      .select('*')
      .eq('product_id', order.product_id)
      .eq('location_id', order.location_id);

    if (order.size_variant) {
      inventoryQuery = inventoryQuery.eq('size_variant', order.size_variant);
    } else {
      inventoryQuery = inventoryQuery.is('size_variant', null);
    }

    const { data: existingInventory, error: invError } = await inventoryQuery.maybeSingle();

    if (invError && invError.code !== 'PGRST116') throw invError;

    // Calculate new average cost and quantity
    const existingQty = existingInventory?.quantity_on_hand || 0;
    const existingCost = existingInventory?.cost_per_unit || 0;
    const newQty = existingQty + order.quantity;
    
    // Average cost calculation
    const newAverageCost = existingQty === 0 
      ? order.unit_cost 
      : ((existingQty * existingCost) + (order.quantity * order.unit_cost)) / newQty;

    if (existingInventory) {
      // Update existing inventory
      const { error: updateError } = await supabase
        .from('inventory_items')
        .update({
          quantity_on_hand: newQty,
          cost_per_unit: Math.round(newAverageCost * 100) / 100,
          updated_at: new Date().toISOString()
        })
        .eq('id', existingInventory.id);

      if (updateError) throw updateError;
    } else {
      // Create new inventory item
      const { error: insertError } = await supabase
        .from('inventory_items')
        .insert({
          product_id: order.product_id,
          location_id: order.location_id,
          size_variant: order.size_variant,
          quantity_on_hand: order.quantity,
          quantity_reserved: 0,
          cost_per_unit: order.unit_cost
        });

      if (insertError) throw insertError;
    }

    // Record inventory movement
    await supabase
      .from('inventory_movements')
      .insert({
        product_id: order.product_id,
        location_id: order.location_id,
        quantity_delta: order.quantity,
        movement_type: 'purchase',
        reason: `Purchase order ${order.order_number} approved`,
        size_variant: order.size_variant,
        unit_cost: order.unit_cost,
        reference_type: 'inventory_order',
        reference_id: order.id
      });

    // Update order status
    const { error: statusError } = await supabase
      .from('inventory_orders')
      .update({
        status: 'approved',
        approved_by: approvedBy,
        approved_at: new Date().toISOString(),
        received_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      })
      .eq('id', orderId);

    if (statusError) throw statusError;

    // Phase 3: post accounting journal for inventory received
    void postInventoryReceivedJournal(orderId);

    toast.success('Order approved and inventory updated');
    return true;
  } catch (error) {
    console.error('Error approving order:', error);
    toast.error('Failed to approve order');
    return false;
  }
};

/**
 * Reject an inventory order
 */
export const rejectInventoryOrder = async (
  orderId: string, 
  rejectedBy: string,
  reason?: string
): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('inventory_orders')
      .update({
        status: 'rejected',
        approved_by: rejectedBy,
        approved_at: new Date().toISOString(),
        notes: reason ? `Rejected: ${reason}` : undefined,
        updated_at: new Date().toISOString()
      })
      .eq('id', orderId)
      .eq('status', 'pending');

    if (error) throw error;

    toast.success('Order rejected');
    return true;
  } catch (error) {
    console.error('Error rejecting order:', error);
    toast.error('Failed to reject order');
    return false;
  }
};

/**
 * Get order by ID
 */
export const getOrderById = async (orderId: string): Promise<InventoryOrder | null> => {
  try {
    const { data, error } = await supabase
      .from('inventory_orders')
      .select(`
        *,
        product:products(name, sku),
        location:inventory_locations(name)
      `)
      .eq('id', orderId)
      .single();

    if (error) throw error;
    return data as InventoryOrder;
  } catch (error) {
    console.error('Error fetching order:', error);
    return null;
  }
};
