// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwdcbfnuywgubumlgscy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZGNiZm51eXdndWJ1bWxnc2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODc3MjQsImV4cCI6MjA2NjM2MzcyNH0.sAT361X6vEMm371diUIzFDj2PN8IKcecwIkpEak0cx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true, // Enable token refresh for security
    persistSession: true, // Enable session persistence for UX
    detectSessionInUrl: true, // Enable URL session detection
    flowType: 'pkce' // Use PKCE flow for better security
  },
  global: {
    // Only add cache headers for non-authentication requests
    fetch: (url: string, options: RequestInit = {}) => {
      const isAuthRequest = url.includes('/auth/') || url.includes('/token');
      
      if (!isAuthRequest) {
        // Only apply cache prevention to non-auth database queries
        const headers = {
          ...(options.headers as Record<string, string> || {}),
          'Cache-Control': 'no-cache, max-age=0',
          'X-Requested-With': 'XMLHttpRequest'
        };
        
        return fetch(url, {
          ...options,
          headers
        });
      }
      
      // For auth requests, use default behavior
      return fetch(url, options);
    }
  }
});