// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwdcbfnuywgubumlgscy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZGNiZm51eXdndWJ1bWxnc2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODc3MjQsImV4cCI6MjA2NjM2MzcyNH0.sAT361X6vEMm371diUIzFDj2PN8IKcecwIkpEak0cx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Use implicit flow for better cross-browser/email client support
    // PKCE requires the same browser session which fails when links are opened from email apps
    flowType: 'implicit'
  }
});